spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dev-template?useUnicode=true&characterEncoding=utf8&verifyServerCertificate=false&useSSL=false&useOldAliasMetadataBehavior=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver